### ISSUE TITLE
Get "program.args.flatMap is not a function" error when using CLI command on windows 10

### ISSUE THREAD

**Issue by romainsauvez** [nfroidure/svgicons2svgfont#95]
## Issue
<!--
When I call this CLI command on Windows 10 : 
svgicons2svgfont --fontname=iconsfont -o src/assets/fonts/iconsfont.svg src/assets/icons/*.svg
I get the error : program.args.flatMap is not a function
(only on windows, no error on Mac OS)

### Expected behavior
Play the command without error like on Mac OS

### Actual behavior
error : program.args.flatMap is not a function

### Steps to reproduce the behavior
just call in terminal on windows 10 : 
svgicons2svgfont --fontname=iconsfont -o src/assets/fonts/iconsfont.svg src/assets/icons/*.svg

### Debugging informations
Windows 10 
GNU bash, version 4.4.23

**Comment by romanlv** [comment]
Same on mac: 
```
svgicons2svgfont --fontname=hello -o font.svg svgs/*.svg
/usr/local/lib/node_modules/svgicons2svgfont/bin/svgicons2svgfont.js:68
const files = program.args.flatMap(file => glob.sync(file));
                           ^

TypeError: program.args.flatMap is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/svgicons2svgfont/bin/svgicons2svgfont.js:68:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by romanlv** [comment]
Looks like it works with latest node `v12`
Easy to install with [n](https://github.com/tj/n) 

`n latest`

**Comment by XhmikosR** [comment]
@nfroidure you can close this
